---

- name: Install ntp
  yum:
    name: ntp
    state: present
  tags: ntp
  become: yes
  become_method: sudo


- name: Configure ntp file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  tags: ntp
  notify: restart ntp
  become: yes
  become_method: sudo


- name: Start the ntp service
  service:
    name: ntpd
    state: started
    enabled: yes
  tags: ntp
  become: yes
  become_method: sudo
