---

- hosts: localhost
  gather_facts: False
  roles:
  - role: download_cdh_management_pkg

- hosts: cluster
  roles:
  - role: common
  - role: ntp
  - role: install_scm_common

- hosts: master
  roles:
  - role: install_scm_server

- hosts: cluster
  roles:
  - role: install_scm_agent
