---

kdc_realm: HADOOP.COM
kdc_db_password: 543210
kdc_admin_password: 012345

kdc_master: kdc1
kdc_slave:
  - kdc2
  - kdc3

master_key_type: aes128-cts
supported_enctypes: "aes256-cts:normal aes128-cts:normal des3-hmac-sha1:normal arcfour-hmac:normal camellia256-cts:normal camellia128-cts:normal des-hmac-sha1:normal des-cbc-md5:normal des-cbc-crc:normal"
