---
# This Playbook runs all the common plays in the deployment

- name: Create the hosts file for all machines
  template: src=hosts.j2 dest=/etc/hosts
  become: yes
  become_method: sudo


- name: write pub ssh key to current user authorized_keys
  authorized_key:
    user: "{{ lookup('env','USER') }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    validate_certs: no
    exclusive: false


- name: install epel repo
  yum:
    pkg: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: installed
  become: yes
  become_method: sudo


- name: install or update system utils
  yum:
    pkg: "{{item}}"
    state: latest
  with_items:
    - tree
    - mariadb
    - mysql-devel
    - ntp
    - htop
    - psmisc
    - bind-utils
    - chkconfig
    - cyrus-sasl-gssapi
    - cyrus-sasl-plain
    - fuse
    - fuse-libs
    - gcc
    - httpd
    - init-functions
    - libxslt
    - mod_ssl
    - MySQL-python
    - openssl
    - openssl-devel
    - openssl-devel
    - perl
    - portmap
    - postgresql-server
    - python
    - python-devel
    - python-psycopg2
    - python-setuptools
    - sed
    - service
    - sqlite
    - swig
    - useradd
    - zlib
  become: yes
  become_method: sudo


- name: make sure /usr/share/java dir exists
  file:
    path: /usr/share/java
    state: directory
  become: yes
  become_method: sudo


- name: copy mysql-connector-java.jar to /usr/share/java
  copy:
    src: "{{ item }}"
    dest: /usr/share/java/"{{ item }}"
  with_items:
    - mysql-connector-java.jar
  become: yes
  become_method: sudo


- name: set timezone to Asia/Shanghai
  timezone:
    name: Asia/Shanghai
  become: yes
  become_method: sudo


- name: disable transparent Huge Pages (THP)
  script: disable_THP.sh
  become: yes
  become_method: sudo


- name: insert/update disable THP configuation block in /etc/rc.local
  blockinfile:
    dest: /etc/rc.local
    block: |
      if [[  -f /sys/kernel/mm/redhat_transparent_hugepage/enabled ]]; then
          echo never > /sys/kernel/mm/redhat_transparent_hugepage/enabled
      fi

      if [[ -f /sys/kernel/mm/redhat_transparent_hugepage/defrag ]]; then
          echo never > /sys/kernel/mm/redhat_transparent_hugepage/defrag
      fi

      if [[ -f /sys/kernel/mm/transparent_hugepage/enabled ]]; then
          echo never > /sys/kernel/mm/transparent_hugepage/enabled
      fi

      if [[ -f /sys/kernel/mm/transparent_hugepage/defrag ]]; then
          echo never > /sys/kernel/mm/transparent_hugepage/defrag
      fi
  become: yes
  become_method: sudo


- name: sysctl vm.swappiness=0
  sysctl:
    name: vm.swappiness
    value: 0
    state: present
  become: yes
  become_method: sudo


- name: stop firewalld and chronyd
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - firewalld
    - chronyd
  become: yes
  become_method: sudo


- name: disable SELinux
  shell: setenforce 0
  become: yes
  become_method: sudo


- name: disable SELinux in /etc/sysconfig/selinux
  ini_file:
    path: /etc/sysconfig/selinux
    section: null
    option: SELINUX
    value: disabled
  become: yes
  become_method: sudo
