---

- hosts: localhost

  vars_files:
  - group_vars/all

  tasks:
  - name: test with_items func
    file:
      path: "{{ item }}"
      state: touch
    with_items:
      - "{{ agent_packages }}"
      - "{{ server_packages }}"
